version: '2'
services:
  service-db:
    image: mysql:5.7.22
    hostname: service-db
    container_name: service-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: st_services
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  registry-1:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: registry-1
    container_name: registry-1
    restart: unless-stopped
    depends_on:
      - service-db
      - registry-migration
    tty: true
    env_file:
      - .one.env
    volumes:
      - app:/var/www
    command:
      - yarn
      - start-dev
  registry-2:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: registry-2
    container_name: registry-2
    restart: unless-stopped
    depends_on:
      - service-db
      - registry-migration
    tty: true
    env_file:
      - .two.env
    volumes:
      - app:/var/www
    command:
      - yarn
      - start-dev
  registry-migration:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: registry-migration
    container_name: registry-migration
    depends_on:
      - service-db
    tty: true
    env_file:
      - .one.env
    volumes:
      - app:/var/www
    command:
      - yarn
      - migrate
  registry-proxy:
    image: nginx:alpine
    container_name: registry-proxy
    restart: unless-stopped
    depends_on:
      - registry-1
      - registry-2
    tty: true
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./

networks:
  default:
    name: 'simple-trader'
    external: true